# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/design_1_PmodAD2_0_0.xci
# IP: The module: 'design_1_PmodAD2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_xlconstant_0_0/PmodAD2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodAD2_xlconstant_0_0 || ORIG_REF_NAME==PmodAD2_xlconstant_0_0} -quiet] -quiet

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_ooc.xdc

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/design_1_PmodAD2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/design_1_PmodAD2_0_0.xci
# IP: The module: 'design_1_PmodAD2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_xlconstant_0_0/PmodAD2_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodAD2_xlconstant_0_0 || ORIG_REF_NAME==PmodAD2_xlconstant_0_0} -quiet] -quiet

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_ooc.xdc

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/design_1_PmodAD2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/emon/Documents/Xilinx/Projects/HPPSI_cora/HPPSI_cora.srcs/sources_1/bd/design_1/ip/design_1_PmodAD2_0_0/src/PmodAD2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
