set_property -dict {PACKAGE_PIN L10 IOSTANDARD LVCMOS33} [get_ports Vp_Vn_0_v_n]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports Vaux1_0_v_p]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports Vaux1_0_v_n]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports Vaux9_0_v_p]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports Vaux9_0_v_n]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports Vaux6_0_v_p]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports Vaux6_0_v_n]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports Vaux15_0_v_p]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports Vaux15_0_v_n]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports Vaux5_0_v_p]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports Vaux5_0_v_n]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports Vaux13_0_v_p]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports Vaux13_0_v_n]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports Vaux0_0_v_p]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports Vaux0_0_v_n]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports Vaux12_0_v_p]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports Vaux12_0_v_n]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports Vaux8_0_v_p]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports Vaux8_0_v_n]


set_property PACKAGE_PIN L20 [get_ports {MUX_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[0]}]
set_property PACKAGE_PIN M20 [get_ports {MUX_EN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[1]}]
set_property PACKAGE_PIN L17 [get_ports {MUX_EN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[2]}]
set_property PACKAGE_PIN U15 [get_ports {MUX_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[3]}]
set_property PACKAGE_PIN R18 [get_ports {MUX_EN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[4]}]
set_property PACKAGE_PIN R17 [get_ports {MUX_EN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[5]}]
set_property PACKAGE_PIN V15 [get_ports {MUX_EN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[6]}]
set_property PACKAGE_PIN T14 [get_ports {MUX_EN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[7]}]
set_property PACKAGE_PIN P20 [get_ports {MUX_EN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[8]}]
set_property PACKAGE_PIN T19 [get_ports {MUX_EN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_EN[9]}]


set_property PACKAGE_PIN G18 [get_ports {MUX_SEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[0]}]
set_property PACKAGE_PIN H18 [get_ports {MUX_SEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[2]}]
set_property PACKAGE_PIN G15 [get_ports {MUX_SEL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[3]}]
set_property PACKAGE_PIN J18 [get_ports {MUX_SEL[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[4]}]
set_property PACKAGE_PIN K18 [get_ports {MUX_SEL[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[5]}]
set_property PACKAGE_PIN M17 [get_ports {MUX_SEL[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[6]}]
set_property PACKAGE_PIN N17 [get_ports {MUX_SEL[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[7]}]
set_property PACKAGE_PIN P18 [get_ports {MUX_SEL[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[8]}]
set_property PACKAGE_PIN M18 [get_ports {MUX_SEL[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[9]}]
set_property PACKAGE_PIN N18 [get_ports {MUX_SEL[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[10]}]
set_property PACKAGE_PIN R14 [get_ports {MUX_SEL[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[11]}]
set_property PACKAGE_PIN T17 [get_ports {MUX_SEL[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[12]}]
set_property PACKAGE_PIN U17 [get_ports {MUX_SEL[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[13]}]
set_property PACKAGE_PIN T16 [get_ports {MUX_SEL[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[14]}]
set_property PACKAGE_PIN V18 [get_ports {MUX_SEL[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[15]}]
set_property PACKAGE_PIN V17 [get_ports {MUX_SEL[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[16]}]
set_property PACKAGE_PIN T15 [get_ports {MUX_SEL[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[17]}]
set_property PACKAGE_PIN U13 [get_ports {MUX_SEL[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[18]}]
set_property PACKAGE_PIN U12 [get_ports {MUX_SEL[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[19]}]
set_property PACKAGE_PIN R16 [get_ports {MUX_SEL[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[20]}]
set_property PACKAGE_PIN V13 [get_ports {MUX_SEL[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[21]}]
set_property PACKAGE_PIN U14 [get_ports {MUX_SEL[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[22]}]
set_property PACKAGE_PIN K19 [get_ports {MUX_SEL[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[23]}]
set_property PACKAGE_PIN P19 [get_ports {MUX_SEL[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[24]}]
set_property PACKAGE_PIN R19 [get_ports {MUX_SEL[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[25]}]
set_property PACKAGE_PIN T20 [get_ports {MUX_SEL[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[26]}]
set_property PACKAGE_PIN U20 [get_ports {MUX_SEL[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[27]}]
set_property PACKAGE_PIN V20 [get_ports {MUX_SEL[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[28]}]
set_property PACKAGE_PIN W20 [get_ports {MUX_SEL[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX_SEL[29]}]



set_property PACKAGE_PIN H17 [get_ports {MUX_SEL[2]}]

